# Generated by Django 4.2.9 on 2024-01-06 09:11

from django.db import migrations


def set_default_site(apps, schema_editor):
    Site = apps.get_model("sites", "Site")
    db_alias = schema_editor.connection.alias

    # Remove default
    Site.objects.using(db_alias).all().delete()

    # Register SITE_ID = 1
    Site.objects.using(db_alias).create(domain="ddt.ron.sh", name="Docker+Django Template")


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.RunPython(set_default_site),
    ]
