# Generated by Django 3.2.5 on 2021-07-31 16:06

from django.db import migrations


def default_site(apps, schema_editor):
    Site = apps.get_model("sites", "Site")
    db_alias = schema_editor.connection.alias

    # Remove default
    Site.objects.using(db_alias).all().delete()

    # Register SITE_ID = 1
    Site.objects.using(db_alias).create(domain="ddt.ron.sh", name="Docker+Django Template")


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(default_site),
    ]
